### PR TITLE
fix: 23

### LINKED ISSUE #23: With isolation enabled tinypool keeps worker count at a minimum
If isolation is enabled `_ensureMinimumWorkers` is called when worker is done. But it only creates a worker if worker count is less then minimum.

Because minimum worker count is half of physical core count right now, this means that Tinypool is using only a quarter of actual PC cores. This is really inefficient. On my 16 core CPU Tinypool is using only 4 cores.

### PR DESCRIPTION
**Pull request by Aslemammad**
Fixes #23

### CODE REVIEW

**Comment by Demivan** [comment]
This would do the trick, but it is the same fix as I did in Vitest. Would be nice if we don't create threads if there is no work for them in the queue.

**Comment by Aslemammad** [comment]
@Demivan Well, as you can see in the code, we create new workers based on maxThreads (L853), So I guess it's good! What's your opinion now?

**Comment by Aslemammad** [comment]
But one thing, we can also make `maxThreads = cpuCount` (physicalCores)  instead of `maxThreads = cpuCount * 1.5`

**Comment by Aslemammad** [comment]
So it'd always see the actual capacity instead of 1.5 or 0.5 of it!

**Comment by Demivan** [comment]
> @Demivan Well, as you can see in the code, we create new workers based on maxThreads (L853), So I guess it's good! What's your opinion now?

Ah, I see it now. Then we can reuse new code for L853 too. Later it can be improved to add workers only if there it work to do.

**Comment by Aslemammad** [comment]
Thanks, @Demivan My system is only 4 cores, it's poor enough, could you try and see if it gains you the performance you need?

**Comment by Demivan** [comment]
Yes, there is a performance boost. It now uses 8 of my cores - that is correct for physical cores config.

We still need to pass config to Tinypool in Vitest because we want different config for watch and run. But we no longer need `minThreads` to be the same as `maxThreads`.

**Comment by Aslemammad** [comment]
Ok then, feel free if this PR improves vitest! Let me merge it! Thank you for your excellent work!

**Pull request merged**
